### PR TITLE
All checkers are loaded automatically from rebasehelper/checkers folder

### PR DESCRIPTION
**Pull request by phracek**
Signed-off-by: Petr Hracek <phracek@redhat.com>

This Pull Request loads all checkers from rebasehelper/checkers dir automatically.
Of course each checkers has to implement required functions.

### CODE REVIEW

**Comment by thozza** [comment]
I think that using entry points and pkg_resources is cleaner approach (http://aroberge.blogspot.cz/2008/12/plugins-part-6-setuptools-based.html), however we can iterate on the solution later.

**Comment by phracek** [comment]
Yeah, seems reasonable.
I would like to move also builders to the similar plugin stuff.

**Comment by phracek** [comment]
What do you think about it. Can we merge it?

**Comment by nforro** [comment]
Fine by me. Just one note: after merging with master, *TestPkgDiff.test_fill_dictionary* and *TestPkgDiff.test_process_xml* fail because tests were moved to *rebasehelper* package and the paths that are being passed to *Checker* class constructor are wrong.

**Pull request merged**
