### PR TITLE
Introduce csmock checker.

### PR DESCRIPTION
**Pull request by phracek**
Signed-off-by: Petr Hracek <phracek@redhat.com>

#147

### CODE REVIEW

**Comment by phracek** [comment]
@nforro @thozza  Feel free to comment it.

**Comment by nforro** [comment]
@phracek: Why is `CommandHelper` class needed? `subprocess.Popen` can search for an executable in `PATH`.

**Comment by nforro** [comment]
@phracek: Actually my point was you can run "csmock" directly with `ProcessHelper.run_subprocess`, you don't have to pass absolute path. Maybe there is some reason why you want to use `CommandHelper.check_command`, but I don't see it.

**Comment by phracek** [comment]
@nforro My point is only to detect whether csmock command exists on system. That's all.
I would like to predict unexpected failure.

**Comment by nforro** [comment]
@phracek: I see. The same thing could be achieved by catching `FileNotFoundError` exception from `ProcessHelper.run_subprocess`, but perhaps your approach is better. The detection could be used also with other checkers, not just with csmock. Also csmock should be listed among other available checkers in command line argument help.

**Comment by phracek** [comment]
@nforro You are right.

**Comment by phracek** [comment]
@nforro Done by the last commit.

**Pull request merged**
